name: Etiquetar Emails con GPT

on:
  schedule:
    - cron: '0 * * * *'  # Cada hora
  workflow_dispatch:         # También puedes ejecutarlo manualmente

jobs:
  etiquetar:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instalar dependencias
        run: |
          pip install openai

      - name: Ejecutar script
        env:
          GMAIL_CREDENTIALS: ${{ secrets.GMAIL_CREDENTIALS }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GMAIL_USER: ${{ secrets.GMAIL_USER }}
        run: python gmail_labels.py
